# Generated by Django 4.2.29 on 2026-09-04 06:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_activation', 'Pending activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='pending_activation', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'financial account',
                'verbose_name_plural': 'financial accounts',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='currency must be an ISO-4217 alpha-3 code in uppercase', regex=re.compile('^[A-Z]{3}$'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='moneycore.financialaccount')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='FinancialCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'financial customer',
                'verbose_name_plural': 'financial customers',
            },
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='moneycore.financialcustomer'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('financial_account', 'currency'), name='moneycore_wallet_unique_currency_per_account'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'closed'])), name='moneycore_wallet_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('currency__regex', '^[A-Z]{3}$')), name='moneycore_wallet_currency_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialcustomer',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'closed'])), name='moneycore_customer_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'closed', 'pending_activation', 'suspended'])), name='moneycore_account_status_valid'),
        ),
    ]
