# Generated by Django 4.2.29 on 2026-09-04 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('moneycore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='currency must be an ISO-4217 alpha-3 code in uppercase', regex=re.compile('^[A-Z]{3}$'))])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='moneycore.journal')),
            ],
            options={
                'verbose_name': 'journal',
                'verbose_name_plural': 'journals',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable internal identifier. Not customer-facing.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Internal label.', max_length=128)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='currency must be an ISO-4217 alpha-3 code in uppercase', regex=re.compile('^[A-Z]{3}$'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account', to='moneycore.wallet')),
            ],
            options={
                'verbose_name': 'ledger account',
                'verbose_name_plural': 'ledger accounts',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount_minor', models.BigIntegerField()),
                ('sequence', models.PositiveSmallIntegerField(help_text='Position within the journal, for stable ordering.')),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='moneycore.journal')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='moneycore.ledgeraccount')),
            ],
            options={
                'verbose_name': 'journal entry',
                'verbose_name_plural': 'journal entries',
                'ordering': ['journal_id', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['currency', 'account_type'], name='moneycore_l_currenc_16138a_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(check=models.Q(('account_type__in', ['asset', 'equity', 'expense', 'liability', 'revenue'])), name='moneycore_ledger_account_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'closed'])), name='moneycore_ledger_account_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(check=models.Q(('currency__regex', '^[A-Z]{3}$')), name='moneycore_ledger_account_currency_format_valid'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['ledger_account', 'direction'], name='moneycore_j_ledger__3bbb9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(check=models.Q(('amount_minor__gt', 0)), name='moneycore_entry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(check=models.Q(('direction__in', ['credit', 'debit'])), name='moneycore_entry_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('journal', 'sequence'), name='moneycore_entry_unique_sequence_per_journal'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['status', 'posted_at'], name='moneycore_j_status_affecb_idx'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'posted'])), name='moneycore_journal_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.CheckConstraint(check=models.Q(('currency__regex', '^[A-Z]{3}$')), name='moneycore_journal_currency_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('posted_at__isnull', False), ('status', 'posted')), models.Q(('posted_at__isnull', True), ('status', 'draft')), _connector='OR'), name='moneycore_journal_posted_at_matches_status'),
        ),
    ]
