# Generated by Django 4.2.29 on 2026-09-04 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('moneycore', '0002_journal_ledgeraccount_journalentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='currency must be an ISO-4217 alpha-3 code in uppercase', regex=re.compile('^[A-Z]{3}$'))])),
                ('amount_minor', models.BigIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='moneycore.wallet')),
            ],
            options={
                'verbose_name': 'funds hold',
                'verbose_name_plural': 'funds holds',
                'indexes': [models.Index(fields=['wallet', 'status', 'expires_at'], name='moneycore_f_wallet__80fa9f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fundshold',
            constraint=models.CheckConstraint(check=models.Q(('amount_minor__gt', 0)), name='moneycore_hold_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundshold',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'expired', 'released'])), name='moneycore_hold_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundshold',
            constraint=models.CheckConstraint(check=models.Q(('currency__regex', '^[A-Z]{3}$')), name='moneycore_hold_currency_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundshold',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('released_at__isnull', False), ('status', 'released')), models.Q(models.Q(('status', 'released'), _negated=True), ('released_at__isnull', True)), _connector='OR'), name='moneycore_hold_released_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='fundshold',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('expired_at__isnull', False), ('status', 'expired')), models.Q(models.Q(('status', 'expired'), _negated=True), ('expired_at__isnull', True)), _connector='OR'), name='moneycore_hold_expired_at_matches_status'),
        ),
    ]
