# Generated by Django 4.2.29 on 2026-09-04 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('moneycore', '0003_fundshold_fundshold_moneycore_hold_amount_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming')], max_length=20)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='currency must be an ISO-4217 alpha-3 code in uppercase', regex=re.compile('^[A-Z]{3}$'))])),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('unknown', 'Unknown'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='created', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('unknown_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hold', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='moneycore.fundshold')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='moneycore.journal')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='moneycore.wallet')),
            ],
            options={
                'verbose_name': 'financial transaction',
                'verbose_name_plural': 'financial transactions',
                'indexes': [models.Index(fields=['wallet', 'status'], name='moneycore_f_wallet__07c972_idx'), models.Index(fields=['status', 'unknown_at'], name='moneycore_f_status_fd85ab_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount_minor__gt', 0)), name='moneycore_txn_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(check=models.Q(('direction__in', ['incoming', 'outgoing'])), name='moneycore_txn_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['created', 'failed', 'processing', 'succeeded', 'unknown'])), name='moneycore_txn_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(check=models.Q(('currency__regex', '^[A-Z]{3}$')), name='moneycore_txn_currency_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'idempotency_key'), name='moneycore_txn_unique_idempotency_key_per_wallet'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('journal__isnull', False), ('status', 'succeeded')), models.Q(models.Q(('status', 'succeeded'), _negated=True), ('journal__isnull', True)), _connector='OR'), name='moneycore_txn_succeeded_requires_journal'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resolved_at__isnull', False), ('status__in', ['failed', 'succeeded'])), models.Q(models.Q(('status__in', ['failed', 'succeeded']), _negated=True), ('resolved_at__isnull', True)), _connector='OR'), name='moneycore_txn_resolved_at_matches_status'),
        ),
    ]
