# Generated by Django 4.2.29 on 2026-09-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneycore', '0004_financialtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=128)),
                ('destination_account_number', models.CharField(max_length=10)),
                ('destination_bank_code', models.CharField(max_length=30)),
                ('destination_bank_name', models.CharField(max_length=128)),
                ('narration', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='moneycore.financialtransaction')),
            ],
            options={
                'verbose_name': 'transfer',
                'verbose_name_plural': 'transfers',
            },
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('destination_account_number__regex', '^[0-9]{10}$')), name='moneycore_transfer_account_number_ngn_format'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('destination_bank_code', ''), _negated=True), name='moneycore_transfer_bank_code_present'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('destination_bank_name', ''), _negated=True), name='moneycore_transfer_bank_name_present'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('recipient_name', ''), _negated=True), name='moneycore_transfer_recipient_name_present'),
        ),
    ]
