# Generated by Django 4.2.29 on 2026-09-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneycore', '0005_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderExecutionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('submit_transfer', 'Submit transfer')], default='submit_transfer', max_length=32)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='started', max_length=20)),
                ('client_reference', models.CharField(max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('ambiguity_reason', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_attempts', to='moneycore.financialtransaction')),
            ],
            options={
                'verbose_name': 'provider execution attempt',
                'verbose_name_plural': 'provider execution attempts',
                'indexes': [models.Index(fields=['status', 'started_at'], name='moneycore_p_status_7f7ee9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['failed', 'started', 'succeeded', 'unknown'])), name='moneycore_attempt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.CheckConstraint(check=models.Q(('operation__in', ['submit_transfer'])), name='moneycore_attempt_operation_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.CheckConstraint(check=models.Q(('provider_key', ''), _negated=True), name='moneycore_attempt_provider_key_present'),
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.CheckConstraint(check=models.Q(('client_reference', ''), _negated=True), name='moneycore_attempt_client_reference_present'),
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.UniqueConstraint(fields=('financial_transaction',), name='moneycore_attempt_one_per_transaction'),
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('finished_at__isnull', False), ('status__in', ['failed', 'succeeded', 'unknown'])), models.Q(models.Q(('status__in', ['failed', 'succeeded', 'unknown']), _negated=True), ('finished_at__isnull', True)), _connector='OR'), name='moneycore_attempt_finished_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.CheckConstraint(check=models.Q(('status', 'failed'), ('failure_code', ''), _connector='OR'), name='moneycore_attempt_failure_code_only_when_failed'),
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.CheckConstraint(check=models.Q(('status', 'unknown'), ('ambiguity_reason', ''), _connector='OR'), name='moneycore_attempt_ambiguity_only_when_unknown'),
        ),
    ]
