# Generated by Django 4.2.29 on 2026-09-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneycore', '0006_provider_execution_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRecoveryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('status_query', 'Status query'), ('webhook', 'Webhook')], max_length=20)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unresolved', 'Unresolved')], max_length=20)),
                ('provider_event_id', models.CharField(blank=True, max_length=128)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'provider recovery evidence',
                'verbose_name_plural': 'provider recovery evidence',
            },
        ),
        migrations.CreateModel(
            name='ProviderWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=64)),
                ('provider_event_id', models.CharField(max_length=128)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unresolved', 'Unresolved')], max_length=20)),
                ('client_reference', models.CharField(blank=True, max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('conflicted', 'Conflicted'), ('unmatched', 'Unmatched')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'provider webhook event',
                'verbose_name_plural': 'provider webhook events',
            },
        ),
        migrations.AddConstraint(
            model_name='providerexecutionattempt',
            constraint=models.UniqueConstraint(fields=('client_reference',), name='moneycore_attempt_unique_client_reference'),
        ),
        migrations.AddField(
            model_name='providerwebhookevent',
            name='provider_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='moneycore.providerexecutionattempt'),
        ),
        migrations.AddField(
            model_name='providerrecoveryevidence',
            name='provider_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_evidence', to='moneycore.providerexecutionattempt'),
        ),
        migrations.AddIndex(
            model_name='providerwebhookevent',
            index=models.Index(fields=['processing_status', 'received_at'], name='moneycore_p_process_a0e9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='providerwebhookevent',
            index=models.Index(fields=['client_reference'], name='moneycore_p_client__692556_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerwebhookevent',
            constraint=models.CheckConstraint(check=models.Q(('outcome__in', ['failed', 'succeeded', 'unresolved'])), name='moneycore_webhook_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerwebhookevent',
            constraint=models.CheckConstraint(check=models.Q(('processing_status__in', ['conflicted', 'processed', 'received', 'unmatched'])), name='moneycore_webhook_processing_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerwebhookevent',
            constraint=models.CheckConstraint(check=models.Q(('provider_key', ''), _negated=True), name='moneycore_webhook_provider_key_present'),
        ),
        migrations.AddConstraint(
            model_name='providerwebhookevent',
            constraint=models.CheckConstraint(check=models.Q(('provider_event_id', ''), _negated=True), name='moneycore_webhook_event_id_present'),
        ),
        migrations.AddConstraint(
            model_name='providerwebhookevent',
            constraint=models.CheckConstraint(check=models.Q(('outcome', 'failed'), ('failure_code', ''), _connector='OR'), name='moneycore_webhook_failure_code_only_when_failed'),
        ),
        migrations.AddConstraint(
            model_name='providerwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider_key', 'provider_event_id'), name='moneycore_webhook_unique_event_per_provider'),
        ),
        migrations.AddIndex(
            model_name='providerrecoveryevidence',
            index=models.Index(fields=['provider_attempt', 'observed_at'], name='moneycore_p_provide_27bc93_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerrecoveryevidence',
            constraint=models.CheckConstraint(check=models.Q(('source__in', ['status_query', 'webhook'])), name='moneycore_evidence_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerrecoveryevidence',
            constraint=models.CheckConstraint(check=models.Q(('outcome__in', ['failed', 'succeeded', 'unresolved'])), name='moneycore_evidence_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerrecoveryevidence',
            constraint=models.CheckConstraint(check=models.Q(('outcome', 'failed'), ('failure_code', ''), _connector='OR'), name='moneycore_evidence_failure_code_only_when_failed'),
        ),
        migrations.AddConstraint(
            model_name='providerrecoveryevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('provider_event_id',), name='moneycore_evidence_unique_provider_event'),
        ),
    ]
