# Generated by Django 4.2.29 on 2026-09-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneycore', '0007_recovery_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=64)),
                ('provider_record_id', models.CharField(blank=True, max_length=128)),
                ('client_reference', models.CharField(blank=True, max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('overall_status', models.CharField(choices=[('matched', 'Matched'), ('discrepancy', 'Discrepancy'), ('provider_only', 'Provider only'), ('internal_only', 'Internal only')], max_length=20)),
                ('provider_outcome', models.CharField(blank=True, choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unresolved', 'Unresolved')], max_length=20)),
                ('internal_outcome', models.CharField(blank=True, choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unresolved', 'Unresolved')], max_length=20)),
                ('provider_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('internal_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('provider_currency', models.CharField(blank=True, max_length=3)),
                ('internal_currency', models.CharField(blank=True, max_length=3)),
                ('outcome_mismatch', models.BooleanField(default=False)),
                ('amount_mismatch', models.BooleanField(default=False)),
                ('currency_mismatch', models.BooleanField(default=False)),
                ('reference_mismatch', models.BooleanField(default=False)),
                ('has_recovery_conflict', models.BooleanField(default=False)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'provider reconciliation item',
                'verbose_name_plural': 'provider reconciliation items',
            },
        ),
        migrations.CreateModel(
            name='ProviderReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed_internal', 'Failed internal')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'provider reconciliation run',
                'verbose_name_plural': 'provider reconciliation runs',
                'indexes': [models.Index(fields=['provider_key', 'window_start'], name='moneycore_p_provide_50cae5_idx'), models.Index(fields=['status', 'started_at'], name='moneycore_p_status_23e696_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationrun',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['completed', 'failed_internal', 'started'])), name='moneycore_recon_run_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationrun',
            constraint=models.CheckConstraint(check=models.Q(('provider_key', ''), _negated=True), name='moneycore_recon_run_provider_key_present'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationrun',
            constraint=models.CheckConstraint(check=models.Q(('window_end__gt', models.F('window_start'))), name='moneycore_recon_run_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationrun',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', False), ('status__in', ['completed', 'failed_internal'])), models.Q(models.Q(('status__in', ['completed', 'failed_internal']), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='moneycore_recon_run_completed_at_matches_status'),
        ),
        migrations.AddField(
            model_name='providerreconciliationitem',
            name='provider_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='moneycore.providerexecutionattempt'),
        ),
        migrations.AddField(
            model_name='providerreconciliationitem',
            name='reconciliation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='moneycore.providerreconciliationrun'),
        ),
        migrations.AddIndex(
            model_name='providerreconciliationitem',
            index=models.Index(fields=['reconciliation_run', 'overall_status'], name='moneycore_p_reconci_843b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='providerreconciliationitem',
            index=models.Index(fields=['client_reference'], name='moneycore_p_client__b9d385_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationitem',
            constraint=models.CheckConstraint(check=models.Q(('overall_status__in', ['discrepancy', 'internal_only', 'matched', 'provider_only'])), name='moneycore_recon_item_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('overall_status', 'matched'), _negated=True), models.Q(('amount_mismatch', False), ('currency_mismatch', False), ('outcome_mismatch', False), ('reference_mismatch', False)), _connector='OR'), name='moneycore_recon_item_matched_has_no_mismatch'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('overall_status', 'discrepancy'), _negated=True), ('outcome_mismatch', True), ('amount_mismatch', True), ('currency_mismatch', True), ('reference_mismatch', True), _connector='OR'), name='moneycore_recon_item_discrepancy_has_a_mismatch'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('overall_status', 'internal_only'), ('provider_record_id', '')), models.Q(models.Q(('overall_status', 'internal_only'), _negated=True), models.Q(('provider_record_id', ''), _negated=True)), _connector='OR'), name='moneycore_recon_item_record_id_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('overall_status', 'provider_only'), ('provider_attempt__isnull', True)), models.Q(models.Q(('overall_status', 'provider_only'), _negated=True), ('provider_attempt__isnull', False)), _connector='OR'), name='moneycore_recon_item_attempt_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_record_id', ''), _negated=True), fields=('reconciliation_run', 'provider_record_id'), name='moneycore_recon_item_one_per_record_per_run'),
        ),
        migrations.AddConstraint(
            model_name='providerreconciliationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_attempt__isnull', False)), fields=('reconciliation_run', 'provider_attempt'), name='moneycore_recon_item_one_per_attempt_per_run'),
        ),
    ]
